[env]
LANG = "en_US.UTF-8"

[terminal.shell]
program = "pwsh.exe"
args = ["-NoLogo", "-NoExit", "-Command", "Set-Location C:\\Users\\olavo; & C:\\Users\\olavo\\AppData\\Roaming\\fastfetch\\pokemon.ps1"]

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
size = 11.5

[window]
opacity = 0.85 # Ajuste entre 0.0 (invisível) e 1.0 (opaco)
blur = true     # Deixa o fundo transparente borrado/focado (estilo Windows Acrylic)